[Desktop]
DesktopShortcuts=Home, Trash, Computer, Network
Wallpaper=/usr/share/backgrounds/swallow/swallow.jpg
WallpaperMode=zoom
WallpaperRandomize=false

[System]
Archiver=xarchiver
FallbackIconThemeName=breeze
Terminal=qterminal

[Window]
AlwaysShowTabs=true
